language: python
python:
  - "3.8"
services:
  - docker

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest

# Run codecov and upload results   
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Build Docker image and deploy to ECR. Then setup ECS Task Definition
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master