language: python
python:
  - "3.8"
services:
  - docker

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov

# command to run tests
script:
  - pytest --cov-report term --cov=tests/

# Run codecov and upload results   
after_success:
  - codecov

# Build Docker image and deploy to ECR. Then setup ECS Task Definition
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master